### ISSUE TITLE
Events date problem

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson-Events-Extension#11]
Hi,

How can I make an event happening each tuesday for X months?
The ony thing I can do is from X to Y, but not each monday from X to Y...

Can you add this option?

Thank you

**Comment by Nic787** [comment]
Ok I did that manually, but now I have a weird problem : http://image.noelshack.com/fichiers/2015/16/1429276213-capture-d-ecran-2015-04-17-a-09-09-46.png

**Comment by Nic787** [comment]
UP!

**Comment by Nic787** [comment]
UP!

I think it should only show the date about the one you clicked on and not all dates.

**Comment by ghost** [comment]
Hello,

We don't support repeated events (there are big technical challenges in achieving this)
