### ISSUE TITLE
Add more options to events

### ISSUE THREAD

**Issue by AnagramEngineering** [ThemeFuse/Unyson-Events-Extension#12]
Hello There, 

i'm trying to extend the events plugin. Unfortunately this is not working, as i was expecting. I always get 

```
Fatal error: Interface 'FW_Events_Interface_Tabs' not found 
```

The manifest looks more or less like this 

``` php
$manifest = array();

$manifest['name']        = __( 'Event-Tickets', 'fw' );
$manifest['description'] = __( '', 'fw' );
$manifest['version'] = '1.0.0';
$manifest['display'] = true;
$manifest['standalone'] = false;


$manifest['requirements'] = array(
    'wordpress' => array(
        'min_version' => '4.0',
    ),
    'extensions' => array(
        'events' => array(),
    )
);
```

But the extension is loaded BEFORE the events itself, thus the interface is not known. 

Does anyone has an idea how this can be done? 

with best regards, 

harry

**Comment by AnagramEngineering** [comment]
moved to wp-types and genesis framework ...

**Comment by ghost** [comment]
The Events extension was made by a developer that is no longer in our team.

I made a search in the whole extension for: `FW_Events_Interface_Tabs` and `fw_get_tabs_options`, and nothing found.

So the documentation seems outdated. We are very sorry. We will investigate this.

**Comment by player0k** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/issues/16 duplicate issue

**Comment by player0k** [comment]
The better way is to remove the interface FW_Events_Interface_Tabs from the repository, and update the documentation with new according conditions for adding new options for the Events extension page
