### ISSUE TITLE
Adding new event or editing existing event - Options are all non-functional

### ISSUE THREAD

**Issue by lineardesign** [ThemeFuse/Unyson-Events-Extension#14]
Greetings,

It seems your **2.4.8** to **2.4.9** update has disabled the event's options. The following are non-functional:
- Event Location **(Search Field / Hidden Fields Toggle)**
- All Day **(Switch)**
- Date and Time **(Addable Option)**

Hopefully this helps, I downloaded the 2.4.8 release and it works, something in the 2.4.9 has killed it. 

If there is anything else I can assist you with in troubleshooting please let me know.

**Comment by llemurya** [comment]
it was fixed , see this issue https://github.com/ThemeFuse/Unyson/issues/968
