### ISSUE TITLE
Can't edit the minute in the datetime-pickers

### ISSUE THREAD

**Issue by jonmlas** [ThemeFuse/Unyson-Events-Extension#15]
Hi,

After updating to the latest Unyson version 2.4.14, I can no longer edit the time of an event. It now goes only through an hourly time manner. I want to be able to select a time like 8:30. Right now, I can only do hourly like 8:00, 9:00, 10:00, etc...
![datetime-picker](https://cloud.githubusercontent.com/assets/13784632/12033950/e4ad5a8c-ae64-11e5-8828-1e8796218ea9.jpg)

I was able to previously edit the time thru typing it but now, it's seem to be locked.

**Comment by llemurya** [comment]
@jonmlas the readonly was set default from this https://github.com/ThemeFuse/Unyson/issues/1086 issue, @danyj please see this issue. I want to know other opinions about the mandatory of the readonly attribute.

**Comment by jonmlas** [comment]
hi @llemurya, how do I overwrite it? I want to be able to edit the minutes.

**Comment by llemurya** [comment]
@jonmlas for now you can see this [issue](https://github.com/ThemeFuse/Unyson/issues/1142). You can specify your `time step`, and user will be able to select the hour from UI , but not change it from input. I want to know if it is ok that input is readonly.

**Comment by jonmlas** [comment]
Thanks, but how do I implement it on Events extension. I mean I want to overwrite the options inside the default Events extension. How do I override the options of an extension?

**Comment by llemurya** [comment]
@jonmlas now it is not possible because it is hardcoded, in the next version it will be an filter in the `event` option-type.

**Comment by jonmlas** [comment]
Thanks @llemurya!

But I would really suggest to add a time step of 30 on the next update. Hope this will be a default for the event.

It is most likely that an event will have a half hour time. Please add this. That would be perfect!

Cheers!

**Comment by llemurya** [comment]
@jonmlas now you can hook and modify the interval.

``` php
add_filter('fw_option_type_event_datetime_pickers', function($data){
    $data['from']['step'] = 10;
    $data['to']['step'] = 10;

    return $data;
});
```

**Comment by jonmlas** [comment]
That's even better! Thanks!
