### ISSUE TITLE
Can't add New options on the Event edit page

### ISSUE THREAD

**Issue by jonmlas** [ThemeFuse/Unyson-Events-Extension#16]
Hi, I can't seem to add a new options on the Event edit page.
![new-options-tab](https://cloud.githubusercontent.com/assets/13784632/12138792/9c523c02-b496-11e5-8b96-15201ec3f277.jpg)

I tried following the instructions in http://manual.unyson.io/en/latest/extension/events/index.html#new-options-on-the-event-edit-page under New options on the Event edit page

Am I missing something? Like the correct filename? I tried adding in all possible filenames used in http://raw-test.readthedocs.org/en/latest/extensions/directory-structure.html#content but still nothing.

Please help. Thanks

**Comment by Niloys7** [comment]
I actually have the same problem :(
I am Developing a Theme for Themeforest and I choose Unyson as my theme framework .
but i need to few more options for developing the theme as like the PSD.
it gives me a Fatal error: Interface 'FW_Events_Interface_Tabs' not found .
i am confused because i can't understand which file i actually need to paste the codes.
Note i also  following the instructions in http://manual.unyson.io/en/latest/extension/events/index.html#new-options-on-the-event-edit-page under New options on the Event edit page.
Thanks

**Comment by player0k** [comment]
Did you make your class which implements **FW_Events_Interface_Tabs** in the sub extension folder of the extension **Events** ?

**Comment by Niloys7** [comment]
No, i don't.
i am a little bit confused about this subfolder structure.
could you please send me the file structure or the folder with code  which add the new edit option.(if you already have it on your draft).
Thanks

**Comment by player0k** [comment]
Try to make your new sub-extension like "events-tags" with your own manifest.php and extension class file in the
theme-folder\framework-customizations\extensions\events\extensions\your-magic-extension\class-fw-extension-your-magic-extension.php

**Comment by Niloys7** [comment]
Still Not working.
maybe i need to research more about it :(

**Comment by player0k** [comment]
In the documentation is described how it was available in the previous version. In last version it is not supported. Try use filter  for adding new options in your function.php file in the root of your theme.

```
add_filter('fw_ext_events_post_options', function($options){
    $new_options= array( 'events_tab_1' => array(
                'title'   => 'test_title',
                'type'    => 'tab',
                'options' => array(
                    'demo_text_id' => array(
                        'type'  => 'text',
                        'desc'  => 'Demo text description',
                        'label' => 'Demo Text Label',
                    )
                )
       )
    );
    return array_merge($options,$new_options);
});
```

**Comment by Niloys7** [comment]
Thank You very much

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Documentation/commit/5aa8a3b99db07a7836387a890436765b30110aff
