### ISSUE TITLE
Events single doesn't appear in menu

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Events-Extension#17]
Events single doesn't appear in menu:
https://static.md/be225dc07c0683fea7f4998e6d049605.png

'show_in_nav_menus'  => false, in class-fw-extension-events.php

**Comment by GheorgheP** [comment]
I don't think that is necessary to add this in core, as adding events posts in menu doesn't make much sense.
But in case you really need this, you can overwrite the `fw-event` post type properties:

```php
function _action_add_events_in_menu() {
	/**
	 * @var FW_Extension_Events $ext
	 */
	$ext   = fw_ext( 'events' );
	$event = (array) get_post_type_object( $ext->get_post_type_name() );

	$event['show_in_nav_menus'] = true;
	register_post_type( $ext->get_post_type_name(), $event );
}

add_action( 'init', '_action_add_events_in_menu' );
```

**Comment by danyj** [comment]
@andronic90 dont use the   action register_post_type in theme, it is  plugin-territory and your theme will not pass Theme Check or TF . This should be in core and is one bool change.

**Comment by andronic90** [comment]
Hi, thank you @danyj I know this

**Comment by GheorgheP** [comment]
@danyj this should not be in core. What will happen then if someone will want to change it to be invisible in menu like it is now?

There are 2 ways:

 - To add a filter in extension that will filter post type options before registering.
 - Make a small plugin for your theme where you'll add all your needs for it.

To be honest i like the second solution, as there are always some specific needs for your theme and placing filters everywhere will not solve all your problems, but will slow down the theme and Unyson for sure.
