### ISSUE TITLE
Conflict with WPML plugin

### ISSUE THREAD

**Issue by GeorgeBotsev** [ThemeFuse/Unyson-Events-Extension#19]
Hello, I am George from WPML.

We have received a ticket: https://wordpress.org/support/topic/fatal-error-on-activation-91?replies=7
In this ticket, you can see, that your plugin, calls for our API code and this leads to the error.
I am writing you to ask for your assistance and that you adjust your code, so that we can avoid such errors.

**Comment by ghost** [comment]
Thanks,

We will fix it.

**Comment by GheorgheP** [comment]
Fixed https://github.com/ThemeFuse/Unyson-Events-Extension/commit/a45a2d4267b2d7727ee57a5e411d685f135d2767
