### ISSUE TITLE
Tranlations problem

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Events-Extension#2]
When I translate events with qtranslate the text come in both languages.
With WPML In Calendar come 2 events ex : http://awesomescreenshot.com/0c24fqb216

**Comment by GheorgheP** [comment]
For those that use qTranslate, in the calendar view `../extensions/shortcodes/shortcodes/calendar/views/view.php` add this code before rendering the calendar:

``` php
if ( function_exists( 'qtrans_getLanguage' ) ) {
    $wrapper_atts['data-ajax-url'] .= '?lang=' . qtrans_getLanguage();
} elseif(function_exists('')){
    //For those that use qTranslate Plus
    $wrapper_atts['data-ajax-url'] .= '?lang=' . ppqtrans_getLanguage();
}
```
