### ISSUE TITLE
manage bookings

### ISSUE THREAD

**Issue by ahm-3d** [ThemeFuse/Unyson-Events-Extension#21]
hi, i was looking into utilizing the events extension until i found out that it doesn't manage bookings. is this something that will be added in the future?

meanwhile i am having to switch the extension off and install this plugin instead: https://en-gb.wordpress.org/plugins/events-manager/

**Comment by player0k** [comment]
Could you please explain what is "manage bookings". How it should work?

**Comment by ahm-3d** [comment]
perhaps an additional post type for bookings, to store all bookings for an event, this could then be extracted as a csv

**Comment by ahm-3d** [comment]
kind of feeling stuck at the moment. the events manager plugin that i downloaded is breaking unyson so i am going to have to abandon this plugin and revisit the unyson event extension.

is there away i can add number of spaces available?

also is there away i can get the form builder to interact with the events extension so you can specify the amount of spaces you would like to book?

**Comment by ghost** [comment]
Hello @ahm-3d 

Unfortunately none of the above features you mentioned are not supported at the moment, and we don't have any plans to add them in the near future.
