### ISSUE TITLE
get_the_category() is returning null

### ISSUE THREAD

**Issue by arvi** [ThemeFuse/Unyson-Events-Extension#25]
Hello, I tried getting the category of a particular event using wordpress `get_the_category()`, however it is returning null even if I have set a category. I want to display category name inside a single post or in taxonomy.

How do I go about this? Thanks a lot.

**Comment by GheorgheP** [comment]
If you look in the `get_the_category()` [doc](https://developer.wordpress.org/reference/functions/get_the_category/), you'll find this note: 

> Note: This function only returns results from the default “**category**” taxonomy. For custom taxonomies use [get_the_terms()](https://developer.wordpress.org/reference/functions/get_the_terms/).

So you should use the the `get_the_terms()` instead.

**Comment by arvi** [comment]
@GheorgheP thanks for the tip! It helped a lot. :smile:
