### ISSUE TITLE
Label for Events Options metabox in Screen Options

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Events-Extension#28]
Hi,

The label for events Options Metabox is empty here in screen options: https://static.md/441b79de32a0677ed79b3e5cd934cb0b.png

**Comment by ViorelEremia** [comment]
Here is no way to do that.
The screen options are rendered here:  https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-screen.php#L1049 function meta_box_prefs, this function dosen't have any hooks: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/screen.php#L99
So if you want to have screen option name add title for container types(meta box): http://manual.unyson.io/en/latest/options/introduction.html#containers
