### ISSUE TITLE
Is it possible to have a link like that: .com/atelier-no-1/ instead of that: .com/fw-event-slug/atelier-no-1/

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Events-Extension#3]
Is it possible to have a link like that: .com/atelier-no-1/ instead of that: .com/fw-event-slug/atelier-no-1/

https://github.com/ThemeFuse/Unyson/issues/310

**Comment by Nic787** [comment]
Where to change that in the php?

**Comment by GheorgheP** [comment]
You can change the slug name by using the `fw_ext_events_post_slug` filter:

``` php
/**
 * Change Events extension post type slug
 * 
 * @param string $slug
 *
 * @return string
 */
function _filter_change_events_slug_name( $slug ) {
    return 'events';
}

add_filter( 'fw_ext_events_post_slug', '_filter_change_events_slug_name' );
```

To remove the slug from permalink, please refer some discussions on this question, about how to remove the slug from permalink of custom posts:
- https://wordpress.org/support/topic/remove-permalink-slug-from-custom-post-type
- http://www.markwarddesign.com/2014/02/remove-custom-post-type-slug-permalink/
- http://kellenmace.com/remove-custom-post-type-slug-from-permalinks/
