### ISSUE TITLE
How to change calendar language?

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Events-Extension#4]
How to change calendar language?

https://github.com/ThemeFuse/Unyson/issues/310

**Comment by Nic787** [comment]
Thank you

Also, I would like two languages for my website, so will it be hard?

**Comment by sergiubagrin** [comment]
> Also, I would like two languages for my website, so will it be hard? 

I opened a new issue for this question: https://github.com/ThemeFuse/Unyson/issues/323

**Comment by sergiubagrin** [comment]
> Also, I would like two languages for my website, so will it be hard?
> I opened a new issue for this question: ThemeFuse/Unyson#323

It is possible to add 2 or more languages with a specific plugin like WPML or Polylang

**Comment by Nic787** [comment]
I have Qtranslate X and the event doesn't want to be translated. Do I need to add the translation manually?

See : http://terra.nicolas-duclos.com/ateliers/

**Comment by Nic787** [comment]
ok, so I downloaded poedit to translate some words from your plugins, but I can't find your po files under languages. Is it normal?

**Comment by GheorgheP** [comment]
Hi,

We are working on this for now. You can use [CodingStyle Localization](https://wordpress.org/plugins/codestyling-localization/) plugin, and you'll be able to translate.

**Comment by Nic787** [comment]
Thank you for the plugin. 

I'm currently translating into french, so I will share you the final work in a couple of days/weeks. Are you ok with that. You will be able to add this language inside Unyson for everyone after.

**Comment by sergiubagrin** [comment]
Hi @Nic787 - Thank you for you r help.

For french translation use this tool: https://www.transifex.com/projects/p/unyson/ Thank you again

**Comment by GheorgheP** [comment]
Hi @Nic787,

About qTranslate, here is a related solution: https://github.com/ThemeFuse/Unyson-Events-Extension/issues/2
