### ISSUE TITLE
Problem with events categories

### ISSUE THREAD

**Issue by Nic787** [ThemeFuse/Unyson-Events-Extension#6]
Hi,

When choosing an event category and linking this one to my calendar, it's not working.
I think there is a problem in the code for that.

I tried removing everything and reinstalling, but I have the same problem.

What we are supposed to have is that when you link your calendar to a certain category, each time you create an event in this category, we are supposed to have the event appearing in the calendar.

Thank you to fixe that. It's annoying. :)

**Comment by GheorgheP** [comment]
Hi,

Sorry for log delay, but if you choose the `All Events` option it works properly?

**Comment by Nic787** [comment]
No. Nothing work. I send a message to Unison for my admin panel. You can try if you want, but don't change theme or other things.

**Comment by GheorgheP** [comment]
Hi,

Please create a dev subdomain where I will be able to test. Idea is that you have a lot of active plugins, especially the qTranslateX plugin. And also, please confirm that you did not made any changes in the Events or Calendar shortcode.

**Comment by Nic787** [comment]
Hi,

The website I'm developping is currently on my dev subdomain, but I can create a personnal backup in case. Also, I didn't change the code and my theme creator doesn't know how to make that work too.

**Comment by GheorgheP** [comment]
Hi,

Please create the backup and tell me, and I will begin the investigation. Also confirm that you agree that I can change all content and settings, and disable plugins

**Comment by Nic787** [comment]
My bakcup is done. You have 3 days to do whatever you want.

**Comment by GheorgheP** [comment]
Hi,

It seems you have a different database table prefixes, and there was a [bug](https://github.com/ThemeFuse/Unyson-Events-Extension/commit/040c083589d9bd6cf9533a182ee405cb84ca7478) in events calendar about this. We solved it and the update will be made [tomorrow](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/46).
