### ISSUE TITLE
Events not appearing

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Events-Extension#8]
https://wordpress.org/support/topic/events-not-appearing-1

Hi,

I have a problem. When I'm creating an event, it's not appearing in my calendar (my calendar is linked to the event category). Maybe a problem in the code, because when I'm in my dashboard, the event link is .com/event1/ but on the page it's .com/fw-event-slug/event1/

Do you think my calendar could work if we remove the slug thing?

PS: I tried to delete and reinstall everything from scratch, but nothing worked.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Events-Extension/commit/040c083589d9bd6cf9533a182ee405cb84ca7478
