### ISSUE TITLE
Events extension takes down entire site

### ISSUE THREAD

**Issue by zeomorph** [ThemeFuse/Unyson-Events-Extension#9]
After enabling Events extension entire website and admin section down, no content on pages.

Apache error log:
PHP Parse error: syntax error, unexpected '[' in /wp-content/plugins/unyson/framework/extensions/events/extensions/events-tags/class-fw-extension-events-tags.php on line 394

Line 394:
https://github.com/ThemeFuse/Unyson-Events-Extension/blob/master/extensions/events-tags/class-fw-extension-events-tags.php#L394):

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson/issues/426#issuecomment-89814792
